Imports System.Windows
Imports System.Windows.Media

Namespace Services
    Public Class ThemeService
        Public Shared Sub Apply(isDarkMode As Boolean)
            If isDarkMode Then
                ApplyDark()
            Else
                ApplyLight()
            End If
        End Sub

        Private Shared Sub ApplyLight()
            ' White, light brown, and dark brown palette
            SetBrush("AccentBrush", "#6B4423")
            SetBrush("AccentDarkBrush", "#4A3228")
            SetBrush("AccentForegroundBrush", "#FFFFFF")
            SetBrush("HeaderBrush", "#3D2B1F")
            SetBrush("PageBackgroundBrush", "#FAF7F4")
            SetBrush("CardBackgroundBrush", "#FFFFFF")
            SetBrush("CardMutedBrush", "#F3EBE3")
            SetBrush("TextBrush", "#3D2B1F")
            SetBrush("MutedTextBrush", "#8B7355")
            SetBrush("AlertBrush", "#F5E6C8")
            SetBrush("LowStockBrush", "#F5D5D5")
            SetBrush("ShellHeaderBrush", "#FFFFFF")
            SetBrush("ShellBorderBrush", "#E8DDD0")
            SetBrush("DrawerBackgroundBrush", "#FFFFFF")
            SetBrush("DrawerBorderBrush", "#D4C4B0")
            SetBrush("ShellIconBrush", "#3D2B1F")
            SetBrush("ShellHoverBrush", "#EDE4D8")
            SetBrush("HeaderStatBrush", "#5C4033")
            SetBrush("DataGridAltRowBrush", "#F8F4F0")
            SetBrush("SecondaryButtonBrush", "#EDE4D8")
            SetBrush("SecondaryButtonHoverBrush", "#E0D2C2")
            SetBrush("SecondaryButtonForegroundBrush", "#5C4033")
            SetBrush("DrawerNavForegroundBrush", "#3D2B1F")
            SetBrush("InputBackgroundBrush", "#FFFFFF")
            SetBrush("InputBorderBrush", "#D4C4B0")
            SetBrush("ChipBackgroundBrush", "#FFFFFF")
            SetBrush("ChipForegroundBrush", "#5C4033")
            SetBrush("ChipBorderBrush", "#D4C4B0")
            SetBrush("ChipHoverBrush", "#F5EDE4")
            SetBrush("CatalogTileHoverBrush", "#F0E6DA")
            SetBrush("NavActiveBackgroundBrush", "#EDE4D8")
            SetBrush("DividerBrush", "#E8DDD0")
            SetBrush("ErrorBrush", "#A52A2A")
            SetBrush("SuccessBadgeBrush", "#E8F0E0")
            SetBrush("WarningBadgeBrush", "#F5E6C8")
            SetBrush("ErrorBadgeBrush", "#F5D5D5")
            SetBrush("AvatarBackgroundBrush", "#EDE4D8")
            SetBrush("AvatarForegroundBrush", "#5C4033")
            SetBrush("NavButtonForegroundBrush", "#8B7355")
            SetBrush("NavButtonHoverBrush", "#5C4033")
            SetBrush("CtaBrush", "#6B4423")
            SetBrush("CtaDarkBrush", "#4A3228")
            SetBrush("CtaForegroundBrush", "#FFFFFF")
            SetBrush("LinkEditBrush", "#2563EB")
            SetBrush("LinkEditHoverBrush", "#1D4ED8")
            SetBrush("LinkDeleteBrush", "#DC2626")
            SetBrush("LinkDeleteHoverBrush", "#B91C1C")
            SetBrush("SearchInputBackgroundBrush", "#FFFFFF")
            SetBrush("InputBorderFocusBrush", "#6B4423")
            SetBrush("ChipActiveBackgroundBrush", "#6B4423")
            SetBrush("ChipInactiveForegroundBrush", "#5C4033")
            SetBrush("ChartFillBrush", "#C8A97E")
        End Sub

        Private Shared Sub ApplyDark()
            ' Warm dark brown palette with stronger contrast
            SetBrush("AccentBrush", "#D4A574")
            SetBrush("AccentDarkBrush", "#C4956A")
            SetBrush("AccentForegroundBrush", "#1A1614")
            SetBrush("HeaderBrush", "#F5EDE4")
            SetBrush("PageBackgroundBrush", "#1A1614")
            SetBrush("CardBackgroundBrush", "#2A2420")
            SetBrush("CardMutedBrush", "#352E28")
            SetBrush("TextBrush", "#F5EDE4")
            SetBrush("MutedTextBrush", "#C4B5A5")
            SetBrush("AlertBrush", "#6B5A3A")
            SetBrush("LowStockBrush", "#6B3A3A")
            SetBrush("ShellHeaderBrush", "#2A2420")
            SetBrush("ShellBorderBrush", "#6B5D52")
            SetBrush("DrawerBackgroundBrush", "#2A2420")
            SetBrush("DrawerBorderBrush", "#6B5D52")
            SetBrush("ShellIconBrush", "#F5EDE4")
            SetBrush("ShellHoverBrush", "#3D342C")
            SetBrush("HeaderStatBrush", "#C4B5A5")
            SetBrush("DataGridAltRowBrush", "#322B26")
            SetBrush("SecondaryButtonBrush", "#4A4038")
            SetBrush("SecondaryButtonHoverBrush", "#5C5048")
            SetBrush("SecondaryButtonForegroundBrush", "#F5EDE4")
            SetBrush("DrawerNavForegroundBrush", "#F5EDE4")
            SetBrush("InputBackgroundBrush", "#352E28")
            SetBrush("InputBorderBrush", "#6B5D52")
            SetBrush("ChipBackgroundBrush", "#352E28")
            SetBrush("ChipForegroundBrush", "#E8DDD0")
            SetBrush("ChipBorderBrush", "#6B5D52")
            SetBrush("ChipHoverBrush", "#4A4038")
            SetBrush("CatalogTileHoverBrush", "#3D342C")
            SetBrush("NavActiveBackgroundBrush", "#3D342C")
            SetBrush("DividerBrush", "#6B5D52")
            SetBrush("ErrorBrush", "#F87171")
            SetBrush("SuccessBadgeBrush", "#2D4A2D")
            SetBrush("WarningBadgeBrush", "#6B5A3A")
            SetBrush("ErrorBadgeBrush", "#6B3A3A")
            SetBrush("AvatarBackgroundBrush", "#3D342C")
            SetBrush("AvatarForegroundBrush", "#D4A574")
            SetBrush("NavButtonForegroundBrush", "#C4B5A5")
            SetBrush("NavButtonHoverBrush", "#4A4038")
            SetBrush("CtaBrush", "#D4A574")
            SetBrush("CtaDarkBrush", "#C4956A")
            SetBrush("CtaForegroundBrush", "#1A1614")
            SetBrush("LinkEditBrush", "#60A5FA")
            SetBrush("LinkEditHoverBrush", "#93C5FD")
            SetBrush("LinkDeleteBrush", "#FB7185")
            SetBrush("LinkDeleteHoverBrush", "#FDA4AF")
            SetBrush("SearchInputBackgroundBrush", "#4A4038")
            SetBrush("InputBorderFocusBrush", "#D4A574")
            SetBrush("ChipActiveBackgroundBrush", "#F0C674")
            SetBrush("ChipInactiveForegroundBrush", "#F5EDE4")
            SetBrush("DialogPrimaryBrush", "#D4A574")
            SetBrush("DialogPrimaryHoverBrush", "#C4956A")
            SetBrush("DialogPrimaryPressedBrush", "#B8875A")
            SetBrush("SoftGoldBrush", "#D4A574")
            SetBrush("ChartFillBrush", "#E0C090")
        End Sub

        Private Shared Sub SetBrush(key As String, hex As String)
            Dim color = CType(ColorConverter.ConvertFromString(hex), Color)
            Dim brush As New SolidColorBrush(color)

            Application.Current.Resources(key) = brush

            For Each merged In Application.Current.Resources.MergedDictionaries
                If merged.Contains(key) Then
                    merged(key) = brush
                End If
            Next
        End Sub
    End Class
End Namespace
